### ISSUE TITLE
Choosing the  five models and not BoxE

### ISSUE THREAD

**Issue by ahmedibatta** [AstraZeneca/kgem-in-drug-discovery#1]
Do you have specific cafeteria for choosing the five models for embedding , are there reasons to do not use  for example BoxE model or PairE model ? 

Thanks ,

**Comment by sbonner0** [comment]
Hey, thanks for your question! The goal of the study was not to find the best overall model (indeed it could be more modern models such as BoxE would have better performance than the models we chose) rather we wanted to study how different factors affected the training of these models. The models we chose were selected based on ones that had been utilised in recent KG+drug discovery papers.

**Comment by ahmedibatta** [comment]
> Hey, thanks for your question! The goal of the study was not to find the best overall model (indeed it could be more modern models such as BoxE would have better performance than the models we chose) rather we wanted to study how different factors affected the training of these models. The models we chose were selected based on ones that had been utilised in recent KG+drug discovery papers.

okay , Thanks for clarifications

**Comment by sbonner0** [comment]
No worries - thanks again for your question.
